.

diff --git a/.github/workflows/deploy_vm.yml b/.github/workflows/deploy_vm.yml
--- a/.github/workflows/deploy_vm.yml
+++ b/.github/workflows/deploy_vm.yml
@@ -1,5 +1,4 @@
-on:
-  workflow_dispatch:
+on: push
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -8,6 +7,8 @@ jobs:
       TF_VAR_gcp_credentials_file: gcp_credentials.json
       TF_VAR_project_id: celestial-opus-418317
       TF_VAR_region: europe-central2
+      TF_LOG: INFO
+      TF_INPUT: false
 
     steps:
       - uses: actions/checkout@v2
@@ -17,8 +18,24 @@ jobs:
           echo "${{ secrets.GCP_SA_KEY }}" > "${{ env.TF_VAR_gcp_credentials_file }}"
         shell: bash
 
-      - name: Terraform Init
-        uses: hashicorp/terraform-github-actions/init@v0.4.0
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.7.5
 
-      - name: Terraform Apply
-        uses: hashicorp/terraform-github-actions/apply@v0.4.0
+      # Run a terraform fmt to check syntax
+      - name: Terraform Format
+        id: fmt
+        run: terraform fmt -check
+
+      # Run a terraform validate
+      - name: Terraform Validate
+        id: validate
+        # Run even if formatting fails
+        if: success() || failure()
+        run: terraform validate -no-color
+
+      - name: Terraform Init and Apply
+        run: |
+          terraform init  
+          terraform apply -auto-approve
